"""
src/fraud_lab.py
------------------
Fraud Lab: attack your own data and measure what InvoiceIQ catches.

It contains NO Streamlit code and never touches the database. Everything runs
in memory:

    real invoices + simulated attack invoices
        -> the SAME features, anomaly model, duplicate rules and risk score the app uses
        -> per-invoice verdict: caught or missed, and why

HOW THE TEST IS KEPT FAIR (for your viva)
  * The anomaly model is the one already trained on your clean data. It has
    never seen the attacks, exactly like a real attack arriving tomorrow.
  * Attack invoices are unpaid and NOT yet due. Late payment is one of the
    strongest risk signals, so if the fakes were overdue they would be caught
    for being late, not for the trick being tested. This way only the trick
    itself is measured.
  * Each attack is generated by simple, visible rules (see the functions
    below) and a seed, so a run can be repeated exactly.
  * The same alarms are also counted on your REAL invoices, so a high catch
    rate cannot hide a detector that flags everything.

LIMITS: the attacks are the ones written here. A real fraudster may behave
differently. A catch rate says how this detector handles these tricks, and
nothing more.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from src.anomaly_detection import score_invoices, train_isolation_forest
from src.duplicate_detection import detect_duplicates
from src.features import build_features
from src.risk_engine import score_risk

# One entry per attack: (key, short title, one-line explanation, what to build if it slips through)
ATTACKS: dict[str, dict] = {
    "spike": {
        "title": "Sudden spike",
        "blurb": "A regular vendor suddenly bills 3 to 6 times its normal amount.",
        "fix": "This is the easy case. If it slips through, lower the amount thresholds in the risk engine.",
    },
    "copy": {
        "title": "Copy-paste duplicate",
        "blurb": "An old invoice is entered again under a new number, same amount, same or next day.",
        "fix": "Exact matches should always raise an alarm. If one is missed, check the duplicate rules.",
    },
    "tweak": {
        "title": "Tweaked duplicate",
        "blurb": "The same invoice again, but the amount is nudged 1 to 5% and the date moved a few days.",
        "fix": "Widen the duplicate rule (for example amounts within 5% and dates within 14 days), "
               "or compare invoice numbers and descriptions as well.",
    },
    "split": {
        "title": "Split under the limit",
        "blurb": "One large bill is cut into three invoices, each just under your approval limit.",
        "fix": "Add a rule: several invoices from one vendor within a few days that together pass the approval limit.",
    },
    "creep": {
        "title": "Creeping price",
        "blurb": "A vendor raises its price about 7% with every invoice, so no single jump looks big.",
        "fix": "Track each vendor's price trend over time, not only one-off jumps.",
    },
    "shell": {
        "title": "Shell vendor",
        "blurb": "A brand-new vendor sends round-number invoices in a quick burst.",
        "fix": "Add a rule for new vendors: round amounts and several invoices in the first weeks.",
    },
}
CHANCE_ATTACKS = ("split", "creep", "shell")
GROUP_SIZE = {"split": 3, "creep": 6, "shell": 6}   # attacks that come as a set of invoices
DEFAULT_LIMIT = 5000.0
SHELL_NAMES = [
    "Apex Holdings", "Bluewater Advisory", "Crestline Partners", "Delta Ridge Services", "Evergreen Consulting",
    "Falcon Point Group", "Granite Peak Solutions", "Harbor Light Trading", "Ironwood Associates", "Juniper Bay Ltd",
    "Keystone Ventures", "Lakeview Support Co", "Meridian Works", "Northgate Supply Group",
]

# The three alarms InvoiceIQ can raise on an invoice.
ALARMS = {
    "risk": "Risk score",
    "anomaly": "Anomaly model",
    "duplicate": "Duplicate check",
}


@dataclass
class LabResult:
    invoices: pd.DataFrame     # one row per attack invoice, with all scores
    real: pd.DataFrame         # the real invoices, scored in the same run
    seed: int
    approval_limit: float
    n_base: int


# ---------------------------------------------------------------------------
# building the fake invoices
# ---------------------------------------------------------------------------
def _vendor_table(base: pd.DataFrame) -> pd.DataFrame:
    """One row per vendor: name, typical (median) amount, usual category, tax rate."""
    g = base.groupby("vendor_id")
    tax_rate = (base["tax"] / base["amount"].replace(0, np.nan)).groupby(base["vendor_id"]).median().fillna(0.0)
    return pd.DataFrame({
        "vendor_name": g["vendor_name"].first(),
        "median": g["amount"].median(),
        "category": g["category"].agg(lambda s: s.mode().iloc[0] if not s.mode().empty else "Other"),
        "tax_rate": tax_rate,
        "n": g["invoice_id"].count(),
    })


class _Builder:
    """Collects attack invoices and keeps them 'unpaid and not yet due' so lateness cannot help detection."""

    def __init__(self, base: pd.DataFrame, rng: np.random.Generator):
        self.base, self.rng = base, rng
        self.vendors = _vendor_table(base)
        self.as_of = max(base["invoice_date"].max(),
                         base["payment_date"].max() if base["payment_date"].notna().any() else base["invoice_date"].max())
        self.rows: list[dict] = []
        self.group = 0

    def add(self, attack: str, vendor_id: str, vendor_name: str, date: pd.Timestamp, amount: float,
            category: str, tax_rate: float, note: str, group: int, src_id: str = "") -> None:
        date = min(pd.Timestamp(date), self.as_of)
        due = max(date + pd.Timedelta(days=30), self.as_of)   # never overdue -> lateness stays out of the test
        amount = round(float(amount), 2)
        self.rows.append({
            "invoice_id": f"ATK-{len(self.rows) + 1:04d}", "vendor_id": vendor_id, "vendor_name": vendor_name,
            "invoice_date": date, "due_date": due, "amount": amount, "tax": round(amount * tax_rate, 2),
            "discount": 0.0, "payment_status": "Pending", "category": category,
            "payment_date": pd.NaT, "payment_delay": np.nan,
            "attack": attack, "group": group, "note": note, "src_id": src_id,
        })

    def next_group(self) -> int:
        self.group += 1
        return self.group

    def recent_date(self, days_back: int) -> pd.Timestamp:
        return self.as_of - pd.Timedelta(days=int(self.rng.integers(0, days_back + 1)))

    def pick_vendor(self, ids=None):
        pool = list(self.vendors.index) if ids is None else list(ids)
        vid = pool[int(self.rng.integers(0, len(pool)))]
        return vid, self.vendors.loc[vid]


def _spike(b: _Builder, n: int, **_):
    for _i in range(n):
        vid, v = b.pick_vendor()
        mult = float(b.rng.uniform(3.0, 6.0))
        b.add("spike", vid, v["vendor_name"], b.recent_date(20), v["median"] * mult, v["category"], v["tax_rate"],
              f"Bills {mult:.1f}x its usual amount", b.next_group())


def _sources(b: _Builder, need_days_after: int) -> pd.DataFrame:
    """Real invoices old enough that a re-entry a few days later still falls inside the data."""
    ok = b.base[b.base["invoice_date"] <= b.as_of - pd.Timedelta(days=need_days_after)]
    return ok if len(ok) else b.base


def _copy(b: _Builder, n: int, **_):
    src = _sources(b, 2)
    for _i in range(n):
        s = src.iloc[int(b.rng.integers(0, len(src)))]
        days = int(b.rng.integers(0, 2))          # same day or next day
        v = b.vendors.loc[s["vendor_id"]]
        b.add("copy", s["vendor_id"], s["vendor_name"], s["invoice_date"] + pd.Timedelta(days=days), s["amount"],
              v["category"], v["tax_rate"], f"Copy of {s['invoice_id']}, same amount, {days} day(s) later",
              b.next_group(), s["invoice_id"])


def _tweak(b: _Builder, n: int, **_):
    src = _sources(b, 12)
    for _i in range(n):
        s = src.iloc[int(b.rng.integers(0, len(src)))]
        pct = float(b.rng.uniform(1.0, 5.0)) * (1 if b.rng.random() < .5 else -1)
        days = int(b.rng.integers(2, 13))
        v = b.vendors.loc[s["vendor_id"]]
        b.add("tweak", s["vendor_id"], s["vendor_name"], s["invoice_date"] + pd.Timedelta(days=days),
              s["amount"] * (1 + pct / 100), v["category"], v["tax_rate"],
              f"Copy of {s['invoice_id']}, amount {pct:+.1f}%, {days} days later", b.next_group(), s["invoice_id"])


def _split(b: _Builder, n: int, approval_limit: float = DEFAULT_LIMIT, **_):
    # split fraud happens where the vendor's normal invoices are near the limit, so pick those vendors
    dist = (np.log(b.vendors["median"].clip(lower=1) / approval_limit)).abs().sort_values()
    close = list(dist.index[: max(3, min(8, len(dist)))])
    for _g in range(max(1, n // GROUP_SIZE["split"])):
        vid, v = b.pick_vendor(close)
        g, start = b.next_group(), b.recent_date(20)
        for k in range(GROUP_SIZE["split"]):
            amount = approval_limit * float(b.rng.uniform(0.90, 0.99))
            b.add("split", vid, v["vendor_name"], start + pd.Timedelta(days=int(b.rng.integers(0, 3))), amount,
                  v["category"], v["tax_rate"],
                  f"Part {k + 1} of 3, each just under the ${approval_limit:,.0f} limit", g)


def _creep(b: _Builder, n: int, **_):
    steps = GROUP_SIZE["creep"]
    for _g in range(max(1, n // steps)):
        vid, v = b.pick_vendor()
        g = b.next_group()
        growth = float(b.rng.uniform(1.06, 1.09))
        level = float(b.rng.uniform(0.95, 1.05))
        start = b.as_of - pd.Timedelta(days=5 * steps + int(b.rng.integers(0, 6)))
        for k in range(steps):
            b.add("creep", vid, v["vendor_name"], start + pd.Timedelta(days=5 * k), v["median"] * level,
                  v["category"], v["tax_rate"], f"Step {k + 1} of {steps}: price now {level:.2f}x normal", g)
            level *= growth


def _shell(b: _Builder, n: int, **_):
    burst = GROUP_SIZE["shell"]
    amounts = b.base["amount"]
    cats = b.base["category"].mode()
    for _g in range(max(1, n // burst)):
        g = b.next_group()
        name = SHELL_NAMES[int(b.rng.integers(0, len(SHELL_NAMES)))]
        vid = f"V-ATK-{g:03d}"
        start = b.as_of - pd.Timedelta(days=int(b.rng.integers(8, 15)))
        base_amt = float(np.quantile(amounts, b.rng.uniform(.55, .9)))
        step = 500 if base_amt >= 2000 else 100
        for k in range(burst):
            amt = max(step, round(base_amt * float(b.rng.uniform(.8, 1.2)) / step) * step)   # round numbers
            b.add("shell", vid, name, start + pd.Timedelta(days=int(b.rng.integers(0, 8))), amt,
                  cats.iloc[0] if len(cats) else "Other", 0.0, f"New vendor, round amount ${amt:,.0f}", g)


_MAKERS = {"spike": _spike, "copy": _copy, "tweak": _tweak, "split": _split, "creep": _creep, "shell": _shell}


def generate_attacks(base: pd.DataFrame, selected: dict[str, int], seed: int = 42,
                     approval_limit: float = DEFAULT_LIMIT) -> pd.DataFrame:
    """Build the fake invoices. `selected` maps attack key -> how many invoices to make (rounded to whole sets)."""
    rng = np.random.default_rng(seed)
    b = _Builder(base, rng)
    for key in ATTACKS:                     # fixed order so a seed always gives the same result
        n = int(selected.get(key, 0))
        if n > 0:
            _MAKERS[key](b, n, approval_limit=approval_limit)
    return pd.DataFrame(b.rows)


# ---------------------------------------------------------------------------
# running the real detectors on real + fake invoices
# ---------------------------------------------------------------------------
def run_lab(base: pd.DataFrame, selected: dict[str, int], bundle: dict | None = None, seed: int = 42,
            approval_limit: float = DEFAULT_LIMIT) -> LabResult:
    """
    Inject the attacks and score everything with the app's own pipeline.

    bundle : the trained anomaly model to use. If None, one is trained on the
             clean invoices first (never on the attacks).
    """
    if base is None or len(base) == 0:
        raise ValueError("There are no invoices to test. Load data first.")
    base = base.reset_index(drop=True)
    attacks = generate_attacks(base, selected, seed, approval_limit)
    if attacks.empty:
        raise ValueError("Pick at least one attack to run.")

    if bundle is None:
        bundle = train_isolation_forest(build_features(base))

    meta_cols = ["attack", "group", "note", "src_id"]
    raw = pd.concat([base, attacks.drop(columns=meta_cols)], ignore_index=True)
    feats = build_features(raw)
    anomaly = score_invoices(bundle, feats)
    dup = detect_duplicates(feats)
    feats = feats.join(dup)
    risk = score_risk(feats, anomaly, duplicate_score=dup["duplicate_score"].values)

    out = feats.copy()
    out["risk_score"] = risk["risk_score"].values
    out["risk_level"] = risk["risk_level"].values
    out["reasons"] = risk["reasons"].values
    out["is_anomaly"] = anomaly["is_anomaly"].values
    out["anomaly_score"] = anomaly["anomaly_score"].values

    n_base = len(base)
    fake = out.iloc[n_base:].copy()
    fake[meta_cols] = attacks[meta_cols].values
    return LabResult(invoices=fake.reset_index(drop=True), real=out.iloc[:n_base].reset_index(drop=True),
                     seed=seed, approval_limit=float(approval_limit), n_base=n_base)


# ---------------------------------------------------------------------------
# judging the result
# ---------------------------------------------------------------------------
def alarms_for(df: pd.DataFrame, min_score: float = 30.0, use: tuple[str, ...] = ("risk", "anomaly", "duplicate")) -> pd.DataFrame:
    """One True/False column per alarm, plus `caught` (any chosen alarm went off)."""
    a = pd.DataFrame(index=df.index)
    a["risk"] = (df["risk_score"] >= min_score) if "risk" in use else False
    a["anomaly"] = df["is_anomaly"].astype(bool) if "anomaly" in use else False
    a["duplicate"] = (df["duplicate_score"] > 0) if "duplicate" in use else False
    a["caught"] = a[["risk", "anomaly", "duplicate"]].any(axis=1)
    return a


def caught_by(row_alarms: pd.Series) -> str:
    names = [ALARMS[k] for k in ("risk", "anomaly", "duplicate") if bool(row_alarms[k])]
    return ", ".join(names) if names else "Nothing"


def why_missed(row: pd.Series) -> str:
    """Plain-English reason an attack invoice stayed quiet, using the real numbers from the run."""
    facts = []
    ratio = float(row["amount_ratio"])
    if ratio < 1.5:
        facts.append(f"the amount is only {ratio:.1f}x the vendor's normal, and the amount score starts at 1.5x")
    if row["attack"] in ("copy", "tweak") and row["duplicate_score"] == 0:
        facts.append("no duplicate rule matched (they need the amount within 1% and the date within 3 days, "
                     "or within 0.1% and 7 days)")
    if row["attack"] == "split":
        facts.append("each invoice on its own is a normal size for this vendor, and no rule adds them together")
    if row["attack"] == "creep" and ratio < 1.5:
        facts.append("each step is only a small rise on the last one")
    if row["attack"] == "shell":
        facts.append("nothing checks for round amounts or a brand-new vendor")
    if not row["is_anomaly"]:
        facts.append("the anomaly model sees nothing odd")
    return f"Scored {row['risk_score']:.0f} of 100: " + "; ".join(facts) + "."


def why_caught(row: pd.Series, alarms: pd.Series) -> str:
    """Short reason an invoice was caught: the strongest risk reasons, or the alarm that fired."""
    reasons = row["reasons"] if isinstance(row["reasons"], list) else []
    if reasons:
        return " ".join(r["text"] for r in reasons[:2])
    if bool(alarms["anomaly"]):
        return "The anomaly model flagged it as unusual."
    return "A duplicate rule matched it."


def summarise(result: LabResult, min_score: float = 30.0,
              use: tuple[str, ...] = ("risk", "anomaly", "duplicate")) -> dict:
    """Numbers for the page: per-attack catch counts, overall rate, and the false-alarm rate on real invoices."""
    inv = result.invoices
    al = alarms_for(inv, min_score, use)
    # "by chance": a set-type attack (split, creep, shell) that only the duplicate check noticed, because two
    # amounts happened to be similar. The detector did not recognise the trick itself.
    al["chance"] = (al["caught"] & ~al["risk"] & ~al["anomaly"] & inv["attack"].isin(CHANCE_ATTACKS))
    real_al = alarms_for(result.real, min_score, use)
    per = []
    for key, meta in ATTACKS.items():
        m = inv["attack"] == key
        if m.any():
            per.append({"key": key, "title": meta["title"], "blurb": meta["blurb"], "fix": meta["fix"],
                        "total": int(m.sum()), "caught": int(al.loc[m, "caught"].sum())})
    total, caught = int(len(inv)), int(al["caught"].sum())
    return {
        "per_attack": per, "total": total, "caught": caught, "chance": int(al["chance"].sum()),
        "rate": caught / total if total else 0.0,
        "false_alarm_rate": float(real_al["caught"].mean()) if len(real_al) else 0.0,
        "false_alarm_n": int(real_al["caught"].sum()), "n_real": int(len(real_al)),
        "alarms": al,
    }


